spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:tcp://localhost:1521/test;NON_KEYWORDS=USER
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: create
  mvc:
    pathmatch:
     matching-strategy: ant_path_matcher